### ISSUE TITLE
Question: about how to replace a tag name in a dom tree

### ISSUE THREAD

**Issue by bitscompagnie** [chishui/JSSoup#1]
Hello,

I just discovered your module and it seems to work well with the examples given.

I have a small project to rename tags in existing document on the file system and store the result with node .js.
How can I change all the p.tagone tags to span.newtag in the dom tree?

Here is an example content for reference.

```
<div>
        <p class="tagone">lorem</p>
        <p class="tagone">lorem</p>
    </div>
    <p class="tagone">lorem</p>
    <p class="tagone">lorem</p>
    <p class="tagone">lorem</p>
    <ul>
        <li class="mytag">lorem</li>
        <li class="mytag">lorem</li>
        <li class="mytag">lorem</li>
        <li class="mytag">lorem</li>
    </ul>
```
And the result should become like below:

```
<div>
        <span class="newtag">lorem</span>
        <span class="newtag">lorem</span>
    </div>
    <span class="newtag">lorem</span>
    <span class="newtag">lorem</span>
    <span class="newtag">lorem</span>
    <ul>
        <li class="mytag">lorem</li>
        <li class="mytag">lorem</li>
        <li class="mytag">lorem</li>
        <li class="mytag">lorem</li>
    </ul>
```
Thanks,

**Comment by chishui** [comment]
Hi, you can try: 
`
var soup = new JSSoup(html);
var ptags = soup.findAll('p');
for (var i = 0; i < ptags.length; ++I) {
ptags[i].name = 'span';
}
console.log(soup.prettify());
`
thanks

**Comment by bitscompagnie** [comment]
Great, it works fine.

I just had to to change the capital I to i in (var i = 0; i < ptags.length; ++I).

So if I had different tags to rename in my source html, what is the way to make the change? Is it possible to do soup.findAll('p', 'li', 'ul') and change them at once? My goal is to change the different tags with new required ones by file. For instance 'p' becomes 'span', 'li' becomes 'p', and 'ul' becomes 'div'.

Thanks a lot for your help.

**Comment by chishui** [comment]
Sorry, it's a typo.
You could enumerate all children elements and change them by your need.
```javascript
var soup = new JSSoup(html);  
var cur = soup.nextElement;
while (cur) {
     if (cur instanceof SoupTag) {
         if (cur.name == 'p')
             do what you want
         else if (cur.name == 'li')
             ...
     }
     cur = cur.nextElement;
}
```

**Comment by bitscompagnie** [comment]
Cool, thanks

**Comment by bitscompagnie** [comment]
I am getting the following error: ReferenceError: SoupTag is not defined, any idea why?

**Comment by chishui** [comment]
please use 
```javascript
if (cur.constructor.name == 'SoupTag') {
```
instead of
```javascript
if (cur instanceof SoupTag) {
```
I will export SoupTag in the future version so that the original code can work.

Thanks,

**Comment by bitscompagnie** [comment]
Thanks a lot, it is working as expected.

**Comment by bitscompagnie** [comment]
Last question/comment: is there a way to select an element based on its class like:

`if (cur.name == 'p[class=mystyle]')` ?

Thanks again.

**Comment by chishui** [comment]
try 
```javascript
if (cur.name = 'p' && cur.attrs.class == 'mystyle')
```

**Comment by bitscompagnie** [comment]
That worked, except that all the tags where the conditions is false get turned into the following:

  <false>
      <false>
        <h2 class="heading">lorem</h2>
        <h2 class="heading">lorem</h2>
      </false>
      <h2 class="heading">lorem</h2>
      <h2 class="heading">lorem</h2>
      <h2 class="heading">lorem</h2>
      <false>
.......

**Comment by bitscompagnie** [comment]
Never mind my last comment, after changing 

` if ( cur.name = 'p' && cur.attrs.class == 'mystyle')`

 to `if (cur.name == 'p' && cur.attrs.class == 'mystyle') `with double == then it all worked fine.

Thanks for your help.

**Comment by bitscompagnie** [comment]
Hello again,
How would you clear inline style like: `<p style="background-color: #C0C0C0"><font face="Times New Roman" size="2">`
Does JSSoup have a method to wrap a group of tags in a new tag? Like creating a new parent node for the the group of tags.

**Comment by chishui** [comment]
Sorry, it cannot create a new tag and wrap others currently.
But there's a workaround I could think about is: create new jssoup for a group of tags, then create another jssoup for the new tag, then use ```append``` to append the group of tags into new tag.

**Comment by bitscompagnie** [comment]
How about clearing inline style?

**Comment by chishui** [comment]
call extract to remove itself from its parent

**Comment by bitscompagnie** [comment]
Ok, good. Will try that.
