### ISSUE TITLE
getText() or .text don't keep double space

### ISSUE THREAD

**Issue by flccrakers** [chishui/JSSoup#11]
When I'm using getText() or text, if there is some child element with more than one space, it seems that the multiple space are collapsed into only one. 
for example in the following html: 
```
<p>
    <span contenteditable="false">﻿﻿﻿﻿﻿﻿﻿﻿blabla bla bla</span>
    <strong style="color: rgb(203, 65, 64);"> </strong> here a double space bla bla
</p>

```
.text will output **blabla bla bla here a double space bla bla**  without the double space.
But this html has been written by the user and the double space need to stay here.

Is it true that the double space are removed or do I do something wrong ?
If true, it should not act like that.

**Comment by chishui** [comment]
I just realized that when parsing html using htmlparser, the "ignoreWhiteSpace" is set to true, so that whitespace inside strong tag and all "\n" are ignored. I should have set it to false. Some logic and test cases need to be fixed.

**Comment by chishui** [comment]
Now you can use ```new JSSoup("<div>asdf</div>", false);``` to disable ignoreWhiteSpace setting.
