### ISSUE TITLE
Update contents of an Element

### ISSUE THREAD

**Issue by SNavleen** [chishui/JSSoup#12]
Hi @chishui,

I was looking at JSSoup it has been very helpful, but I wanted to modify the contents of an element. 

I was able to figure it out, here is the code for reference.

`
 var data = '<div><div class="h1"></div> <div id="d1">Hello World</div></div> ';
 var soup = new JSSoup(data);
 var ele = divSoup.find('div', {'id': 'd1'});
 ele.contents[0]._text = "New Hello World";
`

I just thought that it should be a feature in JSSoup. 

I was hoping I could get an opportunity to implementing it as a feature. Would you be able to provide me with a CONTRIBUTION guide line, just for safety. 

Thanks,
Nav

**Comment by chishui** [comment]
Hi Nav,

I have already been working on adding a "replaceWith" function with which you can replace text. If you want to contribute in the future, you are totally welcome to contribute in any form. The only one guide line is JSSoup is trying to be consistent with BeautifulSoup, so it's easy to use as BeautifulSoup and BeautifulSoup user can have zero friction (ideally) using JSSoup.

Thank,
Liyun

**Comment by markitics** [comment]
This would be awesome! This is my ideal use-case too! 🤞

**Comment by Ankk98** [comment]
Any updates on this??

I want to get all the scripts and replace them in a webpage and save that new webpage.
I am manually trying to do this in a loop for all the descendants but facing difficulty in adding a new object of SoupString to contents[ ] as it is not exported.

**Comment by chishui** [comment]
Fixed in 0.0.12
