### ISSUE TITLE
find by id

### ISSUE THREAD

**Issue by ashkantaravati** [chishui/JSSoup#13]
I need to find an element by its id. I did read the examples but none of them suited my purpose. I started reading your code and I ended up in SoupStrainer's constructor and it looks like it doesn't work with ids.

In my scenario, I have a very dirty HTML from an ASPX file from the medieval age of web development which has all of its parts styled using tables. But there's a specific table with the data I need and it has a class which is not unique and I also can't rely on its index in `findAll` array.

**Comment by JojoSalustiano** [comment]
It's possible do this
`table= soup.find('div', { 'table': 'ctl00_ContentPlaceHolder1_grdWeeklyPlan' })`

**Comment by nazreen** [comment]
the documentation should be updated to mention that second param
