### ISSUE TITLE
Turn off recursive search

### ISSUE THREAD

**Issue by Adman** [chishui/JSSoup#16]
Hello,

is there any option, how to turn off recursive `find`/`findAll` ? I want to find elements among parent's children and not grandchildren.

Example:
```html
<div id="xxx">
    <table>
        <tbody>
            <table class="bad"></table>
        </tbody>
    </table>
</div>
```

```javascript
var div = soup.find('div', {'id': 'xxx'});
console.log(div.findAll('table'))
```
Should return only the first table (with recursive=false), but it also returns the "bad" one.

**Comment by chishui** [comment]
In your example, you can simple use find to replace findAll to get the first table, if you also want to find other table siblings, you can use "findNextSiblings("table")"
