### ISSUE TITLE
prettify() should not output self-closing elements as if they are not self-closing

### ISSUE THREAD

**Issue by jkleiser** [chishui/JSSoup#17]
Self-closing or "void" elements like `<br />` and `<hr />`, and a few others like `<meta charset="utf-8" />` are currently being output by prettify() as if they may have content, like this:
```
   <br>
   </br>
```
That is not very "pretty" in my opinon.
Some info on self-closing elements may be found here: https://htmlreference.io

**Comment by chishui** [comment]
Hi, the tenet of this package is to have the similar behavior with BeautifulSoup4 package in Python.  And in BeautifulSoup4 both <br> and <meta xx /> are outputted by prettify(). If you'd like to filter out those from prettify, could you use extract() to get rid of those self closing elements?

**Comment by chishui** [comment]
Close this issue as no response from requester for very long time.
