### ISSUE TITLE
Preserve formatting for text in <div> tags?

### ISSUE THREAD

**Issue by AirFusion45** [chishui/JSSoup#19]
Hi, 

Wondering if there is a way to preserve the formatting for text in <div> tags. 
For ex: 
```
<div>
<p>bla bla bla</p>
<p>bla bla bla bla</p>
</div>
```
Is there a way to get something along the lines of this (when getting the text of the div):
```bla bla bla\nbla bla bla bla```

Feel free to let me know if anything here is unclear :)
Thanks!

**Comment by keremh** [comment]
Hi @AirFusion45 ,

You can use the command below,

`soup.findAll('p')`

you can have all paragraphs with this code. I hope it works for you :)

**Comment by chishui** [comment]
Could you try to use ```var soup = new JSSoup('<html><head>hello</head></html>', false);``` to keep all whitespaces?

**Comment by AirFusion45** [comment]
I tried that it didn't work. I got it working by parsing it normally and using an HTML cleaner to strip all the tags off but keep the spaces. Thanks though. Closing issue as it's resolved.
