### ISSUE TITLE
how to handle crossorigin ?

### ISSUE THREAD

**Issue by gg4u** [chishui/JSSoup#2]
Does JSSoup works with crossorigin ? 
With beautfiful soup I can open "external" pages:

`soup = BeautifulSoup(urllib2.urlopen(url))`

would be nice if JS could do it to..

**Comment by chishui** [comment]
I think you could try in Javascript as this:
```javascript
fetch(url, {method: 'GET'})
.then((response)=> response.text())
.then((text) => {
    var soup = new JSSoup(text);
    //...
})
```
