### ISSUE TITLE
Typescript Definitions!

### ISSUE THREAD

**Issue by okolawol** [chishui/JSSoup#20]
Hi, thank you for your amazing work! I really appreciate it! Just asking if you are willing to create a typescript definition file for your module?

**Comment by chishui** [comment]
Hey, I don't have a plan to do that. If you want, feel free to make the change and submit a pull request.

**Comment by noxify** [comment]
Maybe a bit late, but you can easily create the definitions by your own.

1. Clone the repo
2. Run `npx tsc lib/*.js --declaration --allowJs --emitDeclarationOnly --outDir types`

In case you're importing the library via

```
import JSSoup from 'jssoup'
```

you have to update the generated `jssoup.d.ts` file like this:

```ts
declare module 'jssoup' {
  // the generated code
}
```

Hope that helps :)

**Comment by MarcelRobitaille** [comment]
Couldn't this be packaged as @types/jssoup making it easier for everyone?

**Comment by MarcelRobitaille** [comment]
Where should I put this file? I get `Could not find a declaration file for module 'jssoup'` no matter where I put it. I also tried setting `typeRoots` and `types` in `tsconfig.json`.

**Comment by noxify** [comment]
@MarcelRobitaille - you're right, having the definitions at `@types` would help.

To your problem, here a Sandbox example: https://codesandbox.io/s/jssoup-example-p9rhut

**Comment by MarcelRobitaille** [comment]
@noxify Thanks for the example. I tried almost the exact same thing with `types/jssoup.d.ts` and `"./types"` in `"typeRoots"`. I'll see if I can find a difference

**Comment by noxify** [comment]
I found the local repo which uses `jssoup` - here the `tsconfig.json` ( last modified 07.2021 🙈 ).

```json
{
  "compilerOptions": {
    "declaration": true,
    "importHelpers": true,
    "module": "commonjs",
    "outDir": "lib",
    "rootDir": "src",
    "strict": true,
    "target": "es2017"
  },
  "include": [
    "src/**/*",
    "types/**/*.d.ts"
  ]
}
```
