### ISSUE TITLE
Image URI

### ISSUE THREAD

**Issue by the-dimensionless** [chishui/JSSoup#22]
Cannot parse Image source={{uri: 'abc'}} successfully

**Comment by chishui** [comment]
Could you provide a more detailed example? I can parse <img> like this
```javascript
var html = `
    <div>
     <img src="img_girl.jpg" alt="Girl in a jacket" width="500" height="600">
    </div>
    `
    var soup = new JSSoup(html);
    var img = soup.find('img');
    console.log(img.attrs['src'])
    console.log(img.attrs['alt'])
    console.log(img.attrs['width'])
    console.log(img.attrs['height'])

```

**Comment by the-dimensionless** [comment]
Hi Chishui/Jssoup

The example you said is very basic form. When used in react native context,
consider following and reply if it works
<Image source={{'abc.png'}} />
<Image source={{uri: 'abc'}} /> Considering abc.png is a pic in android res
folder
<Image
           styles={{style.img}} source = {{'abc'}} />
or
let data = require('./images/')
<Image source={{data[0]}} />

I find it impossible to parse such images in react native.

thank you!

**Comment by chishui** [comment]
The library was designed to parse HTML document not react formatted resource file. So it's not supported.
