### ISSUE TITLE
Published to NPM without dist files?

### ISSUE THREAD

**Issue by apteryxxyz** [chishui/JSSoup#28]
Trying to require/import this produces this error:
`Cannot find module '<path>/dist/lib/jssoup.js'. Please verify that the package.json has a valid "main" entry`.
Looking inside the `node_modules/jssoup` folder, it only contains the `package.json` and `README.md` files.
I'm assuming you published to NPM without including the built files/building the package.

Error: https://runkit.com/embed/7h2ys0pf2e4d
Folder content: https://runkit.com/embed/4gbt57n0yjnc

**Comment by chishui** [comment]
Yes, published another version 0.0.15 fixed it.
