### ISSUE TITLE
Import into Angular2 as a service?

### ISSUE THREAD

**Issue by gitasong** [chishui/JSSoup#3]
Can JSSoup be imported into Angular2 as a service and used with an external URL, like the example below?

```import { Injectable } from '@angular/core';
import { JSSoup } from 'jssoup';

@Injectable()
export class DataScrapingService {

  constructor(private jsSoup: JSSoup) { }

  scrapeData() {
    fetch("https://inciweb.nwcg.gov/incident/5518/", {method: 'GET'})
    .then((response) => response.text())
    .then((text) => {
        var soup = new JSSoup(text);
        soup.find("table.data");
        console.log(soup);
    })
  }

}

**Comment by gitasong** [comment]
Also, in the example above, I'm looking to target the table with class "data" on the given page. Am I using the correct syntax for that? Thanks!

**Comment by chishui** [comment]
I haven't tried to use JSSoup with Angular2. I can't 100% assure you but I think it could. Please give it a try and let me so I can update the document.

To find table with a class data, you should do like this
```javascript
        var soup = new JSSoup(text);
        var data = soup.find("table", "data");
        console.log(data)
```

**Comment by gitasong** [comment]
Perfect; thank you! So far, Angular hasn't thrown any errors with the code above; let's see if I can get it to go all the way, and I'll let you know what I did!
