### ISSUE TITLE
Handling <!DOCTYPE>

### ISSUE THREAD

**Issue by jillson** [chishui/JSSoup#8]
Unless, I'm missing something, when JSSoup gets an HTML document that does the HTML5 encouraged 

&lt; !DOCTYPE html &gt;

 as the first line of the HTML document (which is 100% of the webpages I'm scraping at the moment), using **soup.nextElement.prettify()** outputs 

> &lt;!DOCTYPE>
> </!DOCTYPE>

Demonstration:
```
const JSSoup = require('jssoup').default;
const sampleHTML = "<!DOCTYPE html>\n<html><head><title>Hello</title></head><body>Hello</body></html>";
const soup = new JSSoup(sampleHTML);
console.log(soup.nextElement.prettify());

```

(Expected output would just be sampleHTML)

My current workaround is to strip the DOCTYPE from the input HTML before I call new JSSOUP() and glue it back on afterwards, but that is more of a hack than I'd like.

**Comment by chishui** [comment]
I'll work on that

**Comment by chishui** [comment]
This problem has been fixed

**Comment by edgardleal** [comment]
What version number ? 
I am using `0.0.8` and steel need to remove `<!DOCTYPE html>` using `.substring`

**Comment by oyd11** [comment]
yes, the issue is still here

**Comment by chishui** [comment]
Yeah, you guys are right! However, it's not a bug.
There are two way to skip "DOCTYPE": 
```javascript
    var soup = new JSSoup(text);
    soup.nextElement.nextElement.prettify('','');
```
```javascript
    var soup = new JSSoup(text);
    soup.nextElement.extract();
    soup.nextElement.prettify('','');
```
Thanks

**Comment by oyd11** [comment]
I've skipped it with a regexp; anyhow - where is the actual documentation or example files?
 (I've only read the test, and then some trail and error, and picking at the "node-htmlparser" sources) thanks!

**Comment by chishui** [comment]
You can always check readme for documentation. And you're welcome to submit pull request to make changes.
