### ISSUE TITLE
Get reference to element to change attribute. 

### ISSUE THREAD

**Issue by glennpierce** [chishui/JSSoup#9]
Is it possible to get access to the original elements ?
I want to loop through elements that have either a href or src attribute and rewrite those values.

I can't seem to find a way to do that.

Thanks

**Comment by chishui** [comment]
I'm not sure if I get you right. You can get href or src attributes by  doing this:
```javascript
var soup = new JSSoup('<tag id="hi" class="banner">hello</tag>');
var tag = soup.nextElement;
tag.attrs
// {id: 'hi', class: 'banner'} 
tag.attrs.id = 'test';
console.log(tag)
// <tag id="test" class="banner">hello</tag>
```
